### ISSUE TITLE
Fakultaet rekursiv

### ISSUE THREAD

**Issue by mwhy** [DDeckert/AuD_DDeckert#2]
Hallo,

in der Loesung zur Aufgabe Fakultaet rekursiv ist eine function fac verwendet wurden, die jedoch nicht deklariert ist. Ein Update waere sehr freundlich
int fac_rec(int n);

int main(void){
	int i;
	scanf("%i", &i);
	printf("%d", **fac(i));**

	return 0;
}

int fac_rec(int n){
	if(n==0) return 1;
	else return n***fac(n-1);**
}

**Comment by DDeckert** [comment]
Statt fac müsste da fac_rec stehen.
Korrigiert.
Danke für die Nachricht.
